//
//  Untitled.swift
//  OLMoE.swift
//
//  Created by Stanley Jovel on 11/14/24.
//

import Foundation

protocol Disclaimer {
    var title: String { get }
    var text: String { get }
    var buttonText: String { get }
}

struct Disclaimers {
    struct LimitationDisclaimer: Disclaimer {
        let title = "Limitations"
        let text = """
            Large pretrained language models, such as OLMoE, are trained on [data scraped from the internet](https://arxiv.org/abs/2104.08758), including potentially [toxic](https://spectrum.ieee.org/open-ais-powerful-text-generating-tool-is-ready-for-business), [unethical](https://arxiv.org/abs/2009.06807), and [harmful](https://aclanthology.org/D19-1339/) language, and therefore are quick to output similar content. Ai2 uses several strategies to mitigate these behaviors for the benefit of the general public, but model outputs in the OLMoE App will still contain biases, toxic content, or harmful language. These undesirable results have a legitimate research purpose, however, especially for researchers investigating the sources of bias, toxicity, and harmful language generated by LLMs. 
            """
        let buttonText = "Next \u{02192}"
    }

    struct PrivacyDisclaimer: Disclaimer {
        let title = "Privacy and Data Collection"
        let text = """
            Your data is only shared when you choose to share your conversation. Once you share, you do not have the ability to delete the data you shared. It will be stored and used for future research and educational purposes in the public interest, consistent with Ai2’s mission as a 501(c)(3) nonprofit organization. All retained prompt history and user interaction data you choose to share may be shared outside of Ai2, as permitted by applicable law and Ai2’s policies. Please use your discretion and best judgment when accessing and using the OMLoE app. **NEVER** submit any personal, sensitive, or confidential information in your use of the app.
            """
        let buttonText = "Next \u{02192}"
    }

    struct AcknowledgementDisclaimer: Disclaimer {
        let title = "Acknowledgement"
        let text = """
            'I understand that the OLMoE app may output unintended, inappropriate, or offensive results. I agree to Ai2’s [Terms of Use](https://allenai.org/terms), [Responsible Use Guidelines](https://allenai.org/responsible-use), and [Privacy Policy](https://allenai.org/privacy-policy/). 
            """
        let buttonText = "I Agree"
    }

    struct ShareDisclaimer: Disclaimer {
        let title = "[TODO] Share Disclaimers"
        let text =
            "The Ai2 Playground is intended for research and educational purposes in accordance with our Terms of Use, Responsible Use Guidelines, and Privacy Policy. The Ai2 Playground collects user queries and inputs entered into it as well as other information about the user. You will have 30 days to delete your queries will be stored and used for future research and educational purposes in the public interest consistent with Ai2’s mission as a 501(c)(3) nonprofit organization. All retained prompt history and user interaction data shared with the Ai2 Playground and Dataset Explorer may be shared outside of Ai2, as permitted by applicable law and Ai2’s policies. Please use your discretion and best judgment when accessing and Playground. NEVER submit any personal, sensitive, or confidential your use of the Ai2 Playground or Dataset Explorer."
        let buttonText = "Share"
    }
}
