//
//  Disclaimers.swift
//  OLMoE.swift
//
//  Created by Stanley Jovel on 11/14/24.
//


import Foundation

protocol Disclaimer {
    var title: String { get }
    var text: String { get }
    var headerTextContent: [HeaderTextPair] { get }
    var buttonText: String { get }
}

struct Disclaimers {

    struct FullDisclaimer: Disclaimer {
        let title = "Disclaimer"
        let text = ""
        let buttonText = "Agree"
        let headerTextContent = [
            HeaderTextPair(
                header: "Limitations",
                text: """
                    Large pretrained language models, such as OLMoE, are trained on [data scraped from the internet](https://arxiv.org/abs/2104.08758), including potentially [toxic](https://spectrum.ieee.org/open-ais-powerful-text-generating-tool-is-ready-for-business), [unethical](https://arxiv.org/abs/2009.06807), and [harmful](https://aclanthology.org/D19-1339/) language, and therefore are quick to output similar content. Ai2 uses several strategies to mitigate these behaviors for the benefit of the general public, but model outputs in the OLMoE App will still contain biases, toxic content, or harmful language. These undesirable results have a legitimate research purpose, however, especially for researchers investigating the sources of bias, toxicity, and harmful language generated by LLMs.
                    """),
            HeaderTextPair(
                header: "Privacy and Data Collection",
                text: """
                    Your data is only shared when you choose to share your conversation. Once you share, you do not have the ability to delete the data you shared. It will be stored and used for future research and educational purposes in the public interest, consistent with Ai2’s mission as a 501(c)(3) nonprofit organization. All retained prompt history and user interaction data you choose to share may be shared outside of Ai2, as permitted by applicable law and Ai2’s policies. Please use your discretion and best judgment when accessing and using the OMLoE app. **NEVER** submit any personal, sensitive, or confidential information in your use of the app.
                    """),
            HeaderTextPair(
                header: "Acknowledgement",
                text: """
                    'I understand that the OLMoE app may output unintended, inappropriate, or offensive results. I agree to Ai2’s [Terms of Use](https://allenai.org/terms), [Responsible Use Guidelines](https://allenai.org/responsible-use), and [Privacy Policy](https://allenai.org/privacy-policy/).'
                    """),
        ]
    }

    struct ShareDisclaimer: Disclaimer {
        let title = "Share Disclaimer"
        let text = """
            When sharing a link to a conversation, your messages are transmitted and stored on Ai2's servers.

            You agree to allow Ai2 to collect this interaction data to identify areas for improvement and to develop new features that advance the scientific and educational purposes of Ai2. Once you share a conversation, your data cannot be deleted and will be retained as described in our [Terms of Use](https://allenai.org/terms/2024-09-25) and [Privacy Policy](https://allenai.org/privacy-policy).
            """
        let buttonText = "Share"
        let headerTextContent = [HeaderTextPair]()
    }
}
